# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'python'}

packages = \
['OsuActor', 'OsuActor.actor', 'OsuActor.actor.commands', 'OsuActor.controller']

package_data = \
{'': ['*'], 'OsuActor': ['etc/*']}

install_requires = \
['sdss-access>=0.2.3', 'sdss-tree>=2.15.2', 'sdsstools>=0.4.0']

extras_require = \
{'docs': ['Sphinx>=3.0.0,<4.0.0', 'sphinx_bootstrap_theme>=0.4.12']}

entry_points = \
{'console_scripts': ['OsuActor = OsuActor.__main__:main']}

setup_kwargs = {
    'name': 'sdss-osuactor',
    'version': '0.1.0a0',
    'description': 'Simple Template package for creating SDSS Python projects',
    'long_description': '# OsuActor\n\n![Versions](https://img.shields.io/badge/python->3.7-blue)\n[![Documentation Status](https://readthedocs.org/projects/sdss-OsuActor/badge/?version=latest)](https://sdss-OsuActor.readthedocs.io/en/latest/?badge=latest)\n[![Travis (.org)](https://img.shields.io/travis/sdss/OsuActor)](https://travis-ci.org/sdss/OsuActor)\n[![codecov](https://codecov.io/gh/sdss/OsuActor/branch/main/graph/badge.svg)](https://codecov.io/gh/sdss/OsuActor)\n\nSimple Template package for creating SDSS Python projects\n',
    'author': 'Changgon Kim',
    'author_email': 'changgonkim@khu.ac.kr',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/sdss/OsuActor',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}
from build import *
build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
